[package]
name = "parse_that_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
pprint = { version = "0.3.0", path = "/Users/mkbabb/Programming/pprint" }
regex = "1.11"
parse_that = { version = "0.1.0", path = "../parse_that" }
