[package]
name = "bbnf_derive"
version = "0.1.0"
edition = "2021"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
bbnf = { path = "../" }
pretty = {path = "../../pretty"}

syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
indexmap = "1"
